@startuml context
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(software_developer, "Software Developer", "A developer who wants to fast-delivery a cross-platform frontend application.")
System(beagle, "Beagle", "Allows developers to easily create Beagle Server Driven Screens")
' System(bf, "Beagle Frontend", "Translates Beagle screens to native platform code")
System_Ext(frontend_app, "Frontend Application", "A frontend platform that renders the screens")

Rel(software_developer, beagle, "Develops with")
Rel(frontend_app, beagle, "Renders with")
@enduml
