@startuml c2
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml


Container_Boundary(beagle, "Beagle"){
   
    Component(beagle_container, "In Progress", "")
}


@enduml
