@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

System_Boundary(beagle, "Beagle") {
  
    Container(beagle_backend, "Beagle Backend", "java, kotlin", "Allows creation of screens following the beagle contract")
    
    System_Boundary(beagle_frontend, "Beagle Frontend") {
      
    Container(beagle_web_core, "Beagle Web", "javascript, typescript", "Handles the rendering of beagle web apps")
      Container(beagle_android, "Beagle Android", "kotlin", "Handles the rendering of beagle android apps")
      Container(beagle_ios, "Beagle iOS", "swift", "Handles the rendering of beagle ios apps")
    }
}

System_Ext(frontend_app, "Frontend Application", "A frontend platform that renders the screens")
Person(software_developer, "Software Developer", "A developer who wants to fast-delivery a cross-platform frontend application.")

Rel(software_developer, beagle_backend, "Develops with")
Rel(beagle_frontend, beagle_backend, "Requests beagle UI","HTTPS/JSON")
Rel(frontend_app, beagle_frontend, "Renders with")
Rel(software_developer, frontend_app, "Configures Beagle at")

@enduml
